sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tCxQk228M7Qo4CPLK3h
    access-key-secret: Crv32YBttAGCGWUPO4evAcL3ZlE3ac
    bucket-name: sky-take-out-kilo
